# Configuration for training face latent space

model:
  embedding_dim: 512

training:
  learning_rate: 1e-4
  batch_size: 16
  num_epochs: 50
  save_interval: 10

data:
  image_dir: "path/to/preprocessed/image_data"

output:
  model_save_path: "path/to/save/models"
  log_dir: "path/to/save/logs"
