# Configuration for training face latent space

model:
  embedding_dim: 512

training:
  learning_rate: 1e-4
  batch_size: 16
  num_epochs: 50
  save_interval: 10

data:
  video_dir: "data/processed/video"  # Path to preprocessed video frames

output:
  model_save_path: "output/models/latent"  # Path to save models
  log_dir: "output/logs/latent"  # Path to save logs
